# Netlify Configuration File

[build]
  # Specify the directory where your built files are located
  publish = "."
  command = "npm run build"

[[redirects]]
  # Redirect all traffic to the root path
  from = "/*"
  to = "/"
  status = 200